### ISSUE TITLE
Install : copy-paste a command to create crowdsec_crowdsec.list file

### ISSUE THREAD

**Issue by lucascherifi** [crowdsecurity/crowdsec-docs#10]
In https://packagecloud.io/crowdsec/crowdsec/install#bash-deb

For the `/etc/apt/sources.list.d/crowdsec_crowdsec.list` section

It should be great to just have to copy-paste a command, @see [Docker install doc](https://docs.docker.com/engine/install/debian/) for example:

```sh
 echo \
  "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```

**Comment by buixor** [comment]
present directly in our doc :

![image](https://user-images.githubusercontent.com/990714/124115766-79d21180-da6e-11eb-8a98-13b399d4cde1.png)
