### ISSUE TITLE
How to use captcha with WordPress bouncer?

### ISSUE THREAD

**Issue by nickchomey** [crowdsecurity/crowdsec-docs#238]
There isn't any documentation for the wordpress bouncer on how to configure captcha

https://github.com/crowdsecurity/crowdsec-docs/blob/main/crowdsec-docs/versioned_docs/version-v1.3.0/bouncers/wordpress.mdx

**Comment by buixor** [comment]
Hello,

it's described in the bouncer doc, and the menu should be self-explanatory.

Please let us know if you need more info,
