### ISSUE TITLE
CrowdSec build instructions

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec-docs#426]
CrowdSec since 1.5 has alot more options to build RE2 / WASM / STATIC we should document these options better within docs as currently if you are not internal you dont know how to compile with these options unless you love reading makefiles

**Comment by GoogleSpy81666** [comment]
It's closed why you bother making it news loll .

**Comment by LaurenceJJones** [comment]
> It's closed why you bother making it news loll .

Huh?
