### ISSUE TITLE
[feature-flags] List possible flags?

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec-docs#515]
Currently there is little information about what flags are and what they do

Maybe breakdown feature-flags into different MD files to describe each one in detail

https://docs.crowdsec.net/docs/next/configuration/feature_flags

**Comment by buixor** [comment]
closed via #516

**Comment by buixor** [comment]
closed via https://github.com/crowdsecurity/crowdsec-docs/pull/516
