### ISSUE TITLE
HAProxy bouncer: what does 'local API' mean?

### ISSUE THREAD

**Issue by WilliamDEdwards** [crowdsecurity/crowdsec-docs#677]
The [HAProxy bouncer documentation](https://docs.crowdsec.net/u/bouncers/haproxy/) speaks of a 'local API' (being CrowdSec).

However, many pieces of the documentation show that any (remote) API can be used:

> You must declare a backend for Crowdsec so we're able to resolve it's address during the refresh task.
> replace 127.0.0.1:8080 by the listen URI of the crowdsec local API

etc.

So, what does 'local API' mean in this context?

* 'Local' as in: non-SaaS
* 'Local' as in: on the same machine as the bouncer

**Comment by LaurenceJJones** [comment]
> The [HAProxy bouncer documentation](https://docs.crowdsec.net/u/bouncers/haproxy/) speaks of a 'local API' (being CrowdSec).
> 
> However, many pieces of the documentation show that any (remote) API can be used:
> 
> > You must declare a backend for Crowdsec so we're able to resolve it's address during the refresh task.
> > replace 127.0.0.1:8080 by the listen URI of the crowdsec local API
> 
> etc.
> 
> So, what does 'local API' mean in this context?
> 
>     * 'Local' as in: non-SaaS
> 
>     * 'Local' as in: on the same machine as the bouncer

So this documentation has lacked behind as we do offer integrations which can be used with it, however, it never been tested by us.

So "local api" is the term used to define the API that is exposed by the `CrowdSec` Security Engine as seen by this info graphic https://docs.crowdsec.net/docs/next/intro#architecture
